<?php

/**
 * @file
 * Module definition.
 */

/**
 * Replace a form with the lock widget.
 */
function auth0_theme() {
  return [
    'auth0_login' => [
      'template' => 'auth0-login',
      'variables' => [
        'domain' => NULL,
        'clientID' => NULL,
        'state' => NULL,
        'showSignup' => NULL,
        'widgetCdn' => NULL,
        'loginCSS' => NULL,
        'callbackURL' => NULL,
        'lockExtraSettings' => '{}',
      ],
    ],
  ];
}

/**
 * Handle users deletion, it shoudl delete the auth0 profile.
 */
function auth0_user_delete($account) {
  \Drupal::database()->delete('auth0_user')
    ->condition('drupal_id', $account->uid->value)
    ->execute();
}
