<?php
/**
 * @file
 * Module definition
 */

/**
 * Defines the default JWT leeway.
 */
const AUTH0_JWT_LEEWAY_DEFAULT = 180;

/**
 * Replace a form with the lock widget.
 */
function auth0_theme() {  
  return array(
    'auth0_login' => array(
      'template' => 'auth0-login',
      'variables' => array(
        'domain' => NULL,
        'clientID' => NULL,
        'state' => NULL,
        'showSignup' => NULL,
        'widgetCdn' => NULL,
        'loginCSS' => NULL,
        'callbackURL' => NULL,
        'lockExtraSettings' => '{}',
      ),
    ),
  );
}

/**
 * Handle users deletion, it shoudl delete the auth0 profile.
 */
function auth0_user_delete($account) {
  db_delete('auth0_user')
    ->condition('drupal_id', $account->uid->value)
    ->execute();
}


/**
 * Implements hook_library_info_build().
 */
function auth0_library_info_build() {
  $config = \Drupal::service('config.factory')->get('auth0.settings');
  return [
    'auth0.widget' => [
      'js' => [
        $config->get('auth0_widget_cdn') => [
          'type' => 'external'
        ],
      ],
    ],
  ];
}